---
- name: Configure routers
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: Cleanup config
      ansible.builtin.include_role:
        name: cleanup_config

    - name: Configure interfaces
      ansible.builtin.include_role:
        name: config_ip_interfaces

    - name: Ping interfaces
      loop: "{{ ip_interfaces_config.keys() | list }}"
      loop_control:
        loop_var: router
      ansible.builtin.include_role:
        name: ping_interfaces

    - name: Configure ospf
      ansible.builtin.include_role:
        name: config_ospf

    - name: Ping interfaces
      loop: "{{ ip_interfaces_config.keys() | list }}"
      loop_control:
        loop_var: router
      ansible.builtin.include_role:
        name: ping_interfaces
